### ISSUE TITLE
yolk looks similar to cyclejs

### ISSUE THREAD

**Issue by serapath** [garbles/yolk#55] opened 2015-11-30 14:13 UTC
http://cycle.js.org/

What are the differences?

**Comment by jadbox** [comment] 2015-11-30 16:27
I've tried both: Yolk and Cycle both push into the territory of using ReactiveX streams as the basis for your UI components to interact. While I haven't dived into Cycle, it seems to be more 'proper' and formalized system for how everything comes together into your application. For example, it defines the way you sink and pull data from a database or remote service (using drivers). Yolk tends to be less 'opinionated' and leaves much of the structure up to the developer for how these things may work. In practice, Yolk is easier to pick up, but you may end up needing to explore your own solutions for the application structure; while Cycle has a higher learning barrier but has more rigid (yet clear) definitions for how your app is built. Feel free to correct me @garbles

**Comment by serapath** [comment] 2015-11-30 17:22
thx +1

**Comment by jadbox** [comment] 2015-11-30 17:50
Btw, this is a duplicate of #4

**Comment by garbles** [comment] 2015-12-03 02:10
The explanation from @jadbox is pretty on the money. Cycle offers much more structure and encourages "proper" FRP. I'll close this as it looks like you're satisfied with the response.

**Closed by garbles** 2015-12-03 02:10 UTC
